name: build

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - '**'
  #  paths:
  #    - '**.py'

# this does nothing as expected
defaults:
  run:
    working-directory: ./server

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'server/vrc-patpatpat.spec'
          requirements: 'server/requirements.txt'
          upload_exe_with_name: 'vrc-patpatpat'
  build-windows-debug:
    runs-on: windows-latest
    steps:
      - name: Create Executable with debug enabled
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'server/vrc-patpatpat-debug.spec'
          requirements: 'server/requirements.txt'
          upload_exe_with_name: 'vrc-patpatpat-debug'