name: test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '**.py'

defaults:
    run:
        working-directory: ./server

jobs:
    test:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip setuptools wheel
                pip install -r requirements.txt
            - name: run pytest
              run: |
                  pytest